#!/bin/bash
# Builds "Portfolio Dashboard.app" — a double-clickable launcher that starts
# the local static server (in a Terminal window) and opens the app in your
# browser. Re-run this if you move the project or change your Node install.
#
#   ./scripts/build-launcher.sh
#
set -euo pipefail

# Resolve the repo root from this script's location (portable — no hardcoded paths)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_PATH="$REPO_DIR/Portfolio Dashboard.app"
NODE_BIN="$(command -v node || echo /usr/local/bin/node)"

echo "Repo:  $REPO_DIR"
echo "Node:  $NODE_BIN"

# --- Generate the AppleScript launcher with this machine's paths ---
SRC="$(mktemp /tmp/portfolio-launcher.XXXXXX.applescript)"
cat > "$SRC" <<EOF
-- Portfolio Dashboard launcher (generated by scripts/build-launcher.sh)
-- Click to start the local app and open it in your browser. The server runs
-- in a Terminal window — close that window to stop it. Nothing runs in the
-- background when you are not using it.
on run
	set projectDir to "$REPO_DIR"
	set nodeBin to "$NODE_BIN"
	set alreadyRunning to (do shell script "/usr/sbin/lsof -nP -iTCP:8080 -sTCP:LISTEN > /dev/null 2>&1 && echo yes || echo no")
	if alreadyRunning is "no" then
		tell application "Terminal"
			activate
			do script "clear; cd " & quoted form of projectDir & " && echo 'Portfolio Dashboard server — close this window to stop it.' && exec " & quoted form of nodeBin & " scripts/static-server.js"
		end tell
		delay 1.5
	end if
	do shell script "open http://localhost:8080"
end run
EOF

# --- Compile to an .app bundle ---
rm -rf "$APP_PATH"
osacompile -o "$APP_PATH" "$SRC"
rm -f "$SRC"

# --- Best-effort: give it the portfolio icon (cosmetic; skip on failure) ---
if [ -f "$REPO_DIR/icons/icon-512.png" ]; then
  CLEAN="$(mktemp /tmp/pf-icon.XXXXXX).png"
  ICONSET="$(mktemp -d /tmp/pf-iconset.XXXXXX)/icon.iconset"; mkdir -p "$ICONSET"
  # Re-encode to clean RGB PNG (iconutil rejects some color profiles)
  sips -s format png "$REPO_DIR/icons/icon-512.png" --out "$CLEAN" >/dev/null 2>&1 || true
  for pair in "16:icon_16x16" "32:icon_16x16@2x" "32:icon_32x32" "64:icon_32x32@2x" \
              "128:icon_128x128" "256:icon_128x128@2x" "256:icon_256x256" \
              "512:icon_256x256@2x" "512:icon_512x512" "1024:icon_512x512@2x"; do
    sips -z "${pair%%:*}" "${pair%%:*}" "$CLEAN" --out "$ICONSET/${pair##*:}.png" >/dev/null 2>&1 || true
  done
  if iconutil -c icns "$ICONSET" -o "$APP_PATH/Contents/Resources/applet.icns" 2>/dev/null; then
    echo "Icon:  applied portfolio icon"
  else
    echo "Icon:  (kept default — icon generation skipped)"
  fi
fi

# Clear any quarantine so it double-clicks without a Gatekeeper warning
xattr -dr com.apple.quarantine "$APP_PATH" 2>/dev/null || true
# Nudge Finder/Dock to refresh the icon
touch "$APP_PATH"

echo "Built: $APP_PATH"
echo "Double-click it in Finder (or drag it to your Dock) to launch the app."
